apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: deployment-example
  name: acm-demo-node-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-reader
subjects:
- kind: ServiceAccount
  name: acm-demo
