apiVersion: v1
kind: ConfigMap
metadata:
  name: load-balancer-config
data:
  load-balancer.conf: |
    <Proxy "balancer://mycluster">
    </Proxy>
    ProxyPass        "/" "balancer://mycluster"
    ProxyPassReverse "/" "balancer://mycluster"
