---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: load-balancer
  name: load-balancer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: load-balancer
  sessionAffinity: None
  type: ClusterIP
