---
- hosts: localhost
  vars:
    ansible_python_interpreter: /var/lib/awx/venv/ansible/bin/python
  tasks:
  - set_fact:
      load_balancer_members: []

  - name: Create Balancer Members
    include_tasks: create_balancer_member.yml
    loop: '{{ endpoints }}'
    loop_control:
      loop_var: endpoint
      label: '{{ endpoint }}'

  - name: Create immutable ConfigMap containing new BalancerMember
    k8s:
      host: '{{ hub_api_server }}'
      api_key: '{{ hub_ocp_token }}'
      validate_certs: no
      definition: "{{ lookup('template', './config-map.yml.j2') }}"
      append_hash: true
  
  - name: Patch Deployment to use new ConfigMap
    k8s:
      host: '{{ hub_api_server }}'
      api_key: '{{ hub_ocp_token }}'
      validate_certs: no
      definition: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: load-balancer
          namespace: acm-demo
        spec:
          template:
            spec:
              volumes:
              - name: load-balancer-config
                configMap:
                  name: {{ lookup('template', './config-map.yml.j2') | from_yaml | k8s_config_resource_name }}

