---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-app
  name: demo-app-placement-stable
  namespace: acm-demo
spec:
  clusterSelector:
    matchLabels:
      role: stable