---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-app
  name: demo-app-placement-0
  namespace: acm-demo
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"