---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-app
  name: demo-app-placement-feature-candidate
  namespace: acm-demo
spec:
  clusterSelector:
    matchLabels:
      role: feature-candidate