---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: v2
    apps.open-cluster-management.io/git-path: app
  labels:
    app: demo-app
  name: demo-app-subscription-feature-candidate
  namespace: acm-demo
spec:
  hooksecretref: 
    name: tower-secret
  channel: acm-demo/acm-demo-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-app-placement-feature-candidate
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: v1
    apps.open-cluster-management.io/git-path: app
  labels:
    app: demo-app
  name: demo-app-subscription-stable
  namespace: acm-demo
spec:
  hooksecretref: 
    name: tower-secret
  channel: acm-demo/acm-demo-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-app-placement-stable